// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package models

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
	"go.mongodb.org/mongo-driver/v2/bson"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AssetCondition.
const (
	Fair AssetCondition = "fair"
	Good AssetCondition = "good"
	New  AssetCondition = "new"
	Poor AssetCondition = "poor"
)

// Defines values for AssetStatus.
const (
	Available AssetStatus = "available"
	InRepair  AssetStatus = "in_repair"
	InUse     AssetStatus = "in_use"
	Lost      AssetStatus = "lost"
	Retired   AssetStatus = "retired"
)

// Defines values for AttachmentValidationErrorError.
const (
	AttachmentValidationErrorErrorAlreadyLinked AttachmentValidationErrorError = "already_linked"
	AttachmentValidationErrorErrorNotFound      AttachmentValidationErrorError = "not_found"
	AttachmentValidationErrorErrorNotOwner      AttachmentValidationErrorError = "not_owner"
)

// Defines values for BulkJobStatus.
const (
	BulkJobStatusCompleted           BulkJobStatus = "completed"
	BulkJobStatusCompletedWithErrors BulkJobStatus = "completed_with_errors"
	BulkJobStatusFailed              BulkJobStatus = "failed"
	BulkJobStatusQueued              BulkJobStatus = "queued"
	BulkJobStatusRunning             BulkJobStatus = "running"
)

// Defines values for BulkJobType.
const (
	BulkJobTypeAssign    BulkJobType = "assign"
	BulkJobTypeCondition BulkJobType = "condition"
	BulkJobTypeIds       BulkJobType = "ids"
	BulkJobTypeQr        BulkJobType = "qr"
	BulkJobTypeStatus    BulkJobType = "status"
	BulkJobTypeTransfer  BulkJobType = "transfer"
)

// Defines values for CustomFieldType.
const (
	Boolean CustomFieldType = "boolean"
	Date    CustomFieldType = "date"
	Number  CustomFieldType = "number"
	String  CustomFieldType = "string"
)

// Defines values for ErrorPayloadKind.
const (
	ErrorPayloadKindBadRequest   ErrorPayloadKind = "bad_request"
	ErrorPayloadKindConflict     ErrorPayloadKind = "conflict"
	ErrorPayloadKindForbidden    ErrorPayloadKind = "forbidden"
	ErrorPayloadKindHttpError    ErrorPayloadKind = "http_error"
	ErrorPayloadKindInternal     ErrorPayloadKind = "internal"
	ErrorPayloadKindNotFound     ErrorPayloadKind = "not_found"
	ErrorPayloadKindUnauthorized ErrorPayloadKind = "unauthorized"
	ErrorPayloadKindValidation   ErrorPayloadKind = "validation"
)

// Defines values for ImportConflictPolicy.
const (
	Error        ImportConflictPolicy = "error"
	SkipExisting ImportConflictPolicy = "skipExisting"
)

// Defines values for ImportJobStatus.
const (
	ImportJobStatusCompleted    ImportJobStatus = "completed"
	ImportJobStatusFailed       ImportJobStatus = "failed"
	ImportJobStatusImporting    ImportJobStatus = "importing"
	ImportJobStatusPreviewReady ImportJobStatus = "preview_ready"
	ImportJobStatusRolledBack   ImportJobStatus = "rolled_back"
	ImportJobStatusValidating   ImportJobStatus = "validating"
)

// Defines values for MovementType.
const (
	MovementTypeConditionChange MovementType = "condition_change"
	MovementTypeCustodyChange   MovementType = "custody_change"
	MovementTypeRepairIn        MovementType = "repair_in"
	MovementTypeRepairOut       MovementType = "repair_out"
	MovementTypeStatusChange    MovementType = "status_change"
	MovementTypeTransfer        MovementType = "transfer"
)

// Defines values for NotificationChannel.
const (
	Email NotificationChannel = "email"
)

// Defines values for NotificationStatus.
const (
	Failed NotificationStatus = "failed"
	Queued NotificationStatus = "queued"
	Sent   NotificationStatus = "sent"
)

// Defines values for NotificationType.
const (
	CustodyChange NotificationType = "custody_change"
	Overdue       NotificationType = "overdue"
	RepairUpdate  NotificationType = "repair_update"
	Transfer      NotificationType = "transfer"
)

// Defines values for PurchaseOrderStatus.
const (
	Cancelled PurchaseOrderStatus = "cancelled"
	Draft     PurchaseOrderStatus = "draft"
	Ordered   PurchaseOrderStatus = "ordered"
	Received  PurchaseOrderStatus = "received"
)

// Defines values for RepairStatus.
const (
	Completed    RepairStatus = "completed"
	InProgress   RepairStatus = "in_progress"
	Open         RepairStatus = "open"
	Unrepairable RepairStatus = "unrepairable"
)

// Defines values for Role.
const (
	Admin        Role = "admin"
	Staff        Role = "staff"
	VenueManager Role = "venue_manager"
)

// Asset defines model for Asset.
type Asset struct {
	AssetTag           string         `bson:"assetTag" json:"assetTag"`
	CategoryID         ObjectId       `bson:"categoryId" json:"categoryId"`
	Condition          AssetCondition `bson:"condition" json:"condition"`
	CreatedAt          time.Time      `bson:"createdAt" json:"createdAt"`
	CurrentVenueID     ObjectId       `bson:"currentVenueId" json:"currentVenueId"`
	DepartmentID       *ObjectId      `bson:"departmentId,omitempty" json:"departmentId,omitempty"`
	ExpectedReturnDate *time.Time     `bson:"expectedReturnDate,omitempty" json:"expectedReturnDate,omitempty"`
	HomeVenueID        ObjectId       `bson:"homeVenueId" json:"homeVenueId"`
	ID                 ObjectId       `bson:"_id,omitempty" json:"id"`
	ImportJobID        *ObjectId      `bson:"importJobId,omitempty" json:"importJobId,omitempty"`
	IsActive           bool           `bson:"isActive" json:"isActive"`
	IsOverdue          bool           `bson:"isOverdue" json:"isOverdue"`
	Name               string         `bson:"name" json:"name"`
	Notes              *string        `bson:"notes,omitempty" json:"notes,omitempty"`
	Photos             *[]string      `bson:"photos,omitempty" json:"photos,omitempty"`
	PurchaseDate       *time.Time     `bson:"purchaseDate,omitempty" json:"purchaseDate,omitempty"`
	PurchaseOrderID    *ObjectId      `bson:"purchaseOrderId,omitempty" json:"purchaseOrderId,omitempty"`
	QrToken            string         `bson:"qrToken" json:"qrToken"`
	ResponsibleUserID  *ObjectId      `bson:"responsibleUserId,omitempty" json:"responsibleUserId,omitempty"`
	SerialNumber       *string        `bson:"serialNumber,omitempty" json:"serialNumber,omitempty"`

	// Specs Free-form map of category-defined custom fields.
	Specs     *map[string]interface{} `bson:"specs,omitempty" json:"specs,omitempty"`
	Status    AssetStatus             `bson:"status" json:"status"`
	UpdatedAt time.Time               `bson:"updatedAt" json:"updatedAt"`
}

// AssetCondition defines model for AssetCondition.
type AssetCondition string

// AssetIdsResult The JSON artifact served by GET /assets/bulk/jobs/{jobId}/result for an ids job. assetIds are descending by createdAt (newest first — the most recently created matching assets, with _id as a stable tiebreak, NOT name or relevance), following the GET /assets list sort; when more assets match than limit, the newest `limit` are kept. Ids are as observed during the scan (not a point-in-time snapshot).
type AssetIdsResult struct {
	AssetIDs []ObjectId `json:"assetIds"`

	// Count Number of ids in assetIds (== limit when truncated).
	Count       int       `json:"count"`
	GeneratedAt time.Time `json:"generatedAt"`
	JobID       ObjectId  `json:"jobId"`

	// Truncated True when more assets matched than limit.
	Truncated bool `json:"truncated"`
}

// AssetListFilters Mirrors the GET /assets query parameters EXACTLY (venue, currentVenue, category, department, status, responsible, away, overdue, q) and is kept in lockstep with that parameter list — the same builder (service.BuildAssetListQuery) parses both. All fields optional; an empty/absent object means "everything visible to the caller" (an unfiltered GET /assets), capped by limit and by the caller's venue scope. Malformed ObjectId values yield the same per-field 400 as GET /assets.
type AssetListFilters struct {
	Away         *bool   `json:"away,omitempty"`
	Category     *string `json:"category,omitempty"`
	CurrentVenue *string `json:"currentVenue,omitempty"`
	Department   *string `json:"department,omitempty"`
	Overdue      *bool   `json:"overdue,omitempty"`

	// Q free-text on name/serialNumber/assetTag
	Q           *string `json:"q,omitempty"`
	Responsible *string `json:"responsible,omitempty"`

	// Status Not enum-validated at enqueue (mirrors GET /assets); an unknown value matches zero assets.
	Status *AssetStatus `json:"status,omitempty"`

	// Venue Home venue id.
	Venue *string `json:"venue,omitempty"`
}

// AssetStatus defines model for AssetStatus.
type AssetStatus string

// AssetsByResponsibleRow defines model for AssetsByResponsibleRow.
type AssetsByResponsibleRow struct {
	Count    int      `json:"count"`
	Position *string  `json:"position,omitempty"`
	UserID   ObjectId `json:"userId"`
	UserName string   `json:"userName"`
}

// AssignCustodyRequest defines model for AssignCustodyRequest.
type AssignCustodyRequest struct {
	AttachmentIDs     *[]ObjectId `json:"attachmentIds,omitempty"`
	Notes             *string     `json:"notes,omitempty"`
	ResponsibleUserID ObjectId    `json:"responsibleUserId"`
}

// Attachment Internal attachment record (not returned in full to any API caller).
type Attachment struct {
	AssetIDs    *[]ObjectId `bson:"assetIds,omitempty" json:"assetIds,omitempty"`
	ContentType string      `bson:"contentType" json:"contentType"`
	CreatedAt   time.Time   `bson:"createdAt" json:"createdAt"`
	Filename    string      `bson:"filename" json:"filename"`
	ID          ObjectId    `bson:"_id,omitempty" json:"id"`
	Linked      bool        `bson:"linked" json:"linked"`
	LinkedAt    *time.Time  `bson:"linkedAt,omitempty" json:"linkedAt,omitempty"`
	MovementIDs *[]ObjectId `bson:"movementIds,omitempty" json:"movementIds,omitempty"`
	Size        int64       `bson:"size" json:"size"`
	StorageKey  *string     `bson:"storageKey" json:"storageKey,omitempty"`
	UploadedBy  ObjectId    `bson:"uploadedBy" json:"uploadedBy"`
}

// AttachmentMeta Public attachment metadata embedded in history responses.
type AttachmentMeta struct {
	ContentType string   `json:"contentType"`
	Filename    string   `json:"filename"`
	Id          ObjectId `json:"id"`
	Size        int64    `json:"size"`
}

// AttachmentUploadResponse defines model for AttachmentUploadResponse.
type AttachmentUploadResponse struct {
	AttachmentId ObjectId `json:"attachmentId"`
	ContentType  string   `json:"contentType"`
	Filename     string   `json:"filename"`
	Size         int64    `json:"size"`
}

// AttachmentValidationError defines model for AttachmentValidationError.
type AttachmentValidationError struct {
	AttachmentId ObjectId                        `json:"attachmentId"`
	Error        *AttachmentValidationErrorError `json:"error,omitempty"`
	Ok           bool                            `json:"ok"`
}

// AttachmentValidationErrorError defines model for AttachmentValidationError.Error.
type AttachmentValidationErrorError string

// AttachmentValidationResponse Returned as the 400 body when action-time attachment validation fails.
// The top-level 'attachments' array is only present for Phase-B failures
// (per-attachment checks). Phase-A gate failures (too_many, duplicate_id)
// return only the 'error' payload.
type AttachmentValidationResponse struct {
	Attachments *[]AttachmentValidationError `json:"attachments,omitempty"`
	Error       ErrorPayload                 `json:"error"`
}

// AuditLog defines model for AuditLog.
type AuditLog struct {
	Action      string                  `bson:"action" json:"action"`
	Changes     *map[string]interface{} `bson:"changes,omitempty" json:"changes,omitempty"`
	EntityID    ObjectId                `bson:"entityId" json:"entityId"`
	EntityType  string                  `bson:"entityType" json:"entityType"`
	ID          ObjectId                `bson:"_id,omitempty" json:"id"`
	Ip          *string                 `bson:"ip,omitempty" json:"ip,omitempty"`
	PerformedAt time.Time               `bson:"performedAt" json:"performedAt"`
	PerformedBy ObjectId                `bson:"performedBy" json:"performedBy"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Tokens TokenPair `json:"tokens"`
	User   User      `json:"user"`
}

// BulkActionResponse defines model for BulkActionResponse.
type BulkActionResponse struct {
	Failed    int                `json:"failed"`
	Results   []BulkActionResult `json:"results"`
	Succeeded int                `json:"succeeded"`
	Total     int                `json:"total"`
}

// BulkActionResult defines model for BulkActionResult.
type BulkActionResult struct {
	AssetID ObjectId `json:"assetId"`

	// Error Present iff ok=false. Per-row reason: not_found, forbidden, invalid_transition, dest_venue_forbidden, etc.
	Error *string `json:"error,omitempty"`
	Ok    bool    `json:"ok"`
}

// BulkAssignRequest defines model for BulkAssignRequest.
type BulkAssignRequest struct {
	AssetIDs          []ObjectId  `json:"assetIds"`
	AttachmentIDs     *[]ObjectId `json:"attachmentIds,omitempty"`
	Notes             *string     `json:"notes,omitempty"`
	ResponsibleUserID ObjectId    `json:"responsibleUserId"`

	// ValidOnly If true, enqueue the valid rows and record invalid ones as job row errors instead of failing the whole request. Default false (strict: any invalid row → 400, nothing enqueued). Note: an unknown/inactive responsibleUserId is always a whole-request 400 regardless of this flag.
	ValidOnly *bool `json:"validOnly,omitempty"`
}

// BulkAssignResponse defines model for BulkAssignResponse.
type BulkAssignResponse struct {
	Results []BulkActionResult `json:"results"`

	// SkippedNoOp Assets already assigned to responsibleUserId; no movement written.
	SkippedNoOp int `json:"skippedNoOp"`
	Total       int `json:"total"`

	// Updated Assets whose responsibleUserId changed; one custody_change Movement was written for each.
	Updated int `json:"updated"`
}

// BulkConditionResult defines model for BulkConditionResult.
type BulkConditionResult struct {
	Skipped []BulkConditionSkipped `json:"skipped"`
	Updated int                    `json:"updated"`
}

// BulkConditionSkipped defines model for BulkConditionSkipped.
type BulkConditionSkipped struct {
	ID ObjectId `json:"id"`

	// Reason One of: not_found, forbidden, unchanged.
	Reason string `json:"reason"`
}

// BulkConditionUpdate defines model for BulkConditionUpdate.
type BulkConditionUpdate struct {
	AssetIDs      []ObjectId     `json:"assetIds"`
	AttachmentIDs *[]ObjectId    `json:"attachmentIds,omitempty"`
	Condition     AssetCondition `json:"condition"`
	Notes         *string        `json:"notes,omitempty"`

	// ValidOnly Accepted for symmetry with the other bulk actions. The condition job is best-effort by design: no-op/not-found/forbidden rows are counted as skips, not errors, so this flag has no effect on enqueue outcome.
	ValidOnly *bool `json:"validOnly,omitempty"`
}

// BulkIdsRequest Enqueue an async asset-id export. filters mirrors GET /assets; limit caps the result.
type BulkIdsRequest struct {
	Filters *AssetListFilters `json:"filters,omitempty"`

	// Limit Max ids to collect (1..ASSET_IDS_MAX_LIMIT). Optional; defaults to the server cap.
	Limit *int `json:"limit,omitempty"`
}

// BulkJob defines model for BulkJob.
type BulkJob struct {
	CompletedAt *time.Time    `bson:"completedAt,omitempty" json:"completedAt,omitempty"`
	Counts      BulkJobCounts `bson:"counts" json:"counts"`
	CreatedAt   time.Time     `bson:"createdAt" json:"createdAt"`

	// Errors Row-level errors, capped (see errorsTruncated).
	Errors []BulkJobRowError `bson:"errors" json:"errors"`

	// ErrorsTruncated True when more row errors occurred than are retained in errors[].
	ErrorsTruncated bool            `bson:"errorsTruncated" json:"errorsTruncated"`
	ID              ObjectId        `bson:"_id,omitempty" json:"id"`
	Progress        BulkJobProgress `bson:"progress" json:"progress"`

	// RequestedBy The enqueuing principal. Authorization is evaluated once, at enqueue; every Movement is stamped performedBy = this principal.
	RequestedBy ObjectId      `bson:"requestedBy" json:"requestedBy"`
	StartedAt   *time.Time    `bson:"startedAt,omitempty" json:"startedAt,omitempty"`
	Status      BulkJobStatus `bson:"status" json:"status"`
	Type        BulkJobType   `bson:"type" json:"type"`
}

// BulkJobCounts defines model for BulkJobCounts.
type BulkJobCounts struct {
	Failed int `bson:"failed" json:"failed"`

	// Skipped No-op rows (e.g. already-assigned custody, unchanged condition).
	Skipped   int `bson:"skipped" json:"skipped"`
	Succeeded int `bson:"succeeded" json:"succeeded"`

	// Total Deduped assetIds enqueued.
	Total int `bson:"total" json:"total"`
}

// BulkJobList defines model for BulkJobList.
type BulkJobList struct {
	Jobs []BulkJob `json:"jobs"`
}

// BulkJobProgress defines model for BulkJobProgress.
type BulkJobProgress struct {
	// BatchesDone Batches whose transaction has committed. Advances only inside committed batch txns, so it is crash-safe.
	BatchesDone  int `bson:"batchesDone" json:"batchesDone"`
	BatchesTotal int `bson:"batchesTotal" json:"batchesTotal"`
}

// BulkJobRowError defines model for BulkJobRowError.
type BulkJobRowError struct {
	AssetID ObjectId `bson:"assetId" json:"assetId"`

	// Code Per-row reason, e.g. not_found, forbidden, invalid_transition, dest_venue_forbidden.
	Code    string `bson:"code" json:"code"`
	Message string `bson:"message" json:"message"`
}

// BulkJobStatus queued (awaiting a worker), running (claimed, batches executing), completed (all batches done, zero row errors), completed_with_errors (done, some rows failed/skipped-as-error), failed (zero successes or a fatal infrastructure error).
type BulkJobStatus string

// BulkJobType transfer/status/assign/condition mutate assets in batched transactions; qr renders a combined PDF artifact; ids exports asset _ids matching a GET /assets filter set as a JSON artifact.
type BulkJobType string

// BulkQrRequest defines model for BulkQrRequest.
type BulkQrRequest struct {
	AssetIDs []ObjectId `json:"assetIds"`
}

// BulkStatusRequest defines model for BulkStatusRequest.
type BulkStatusRequest struct {
	AssetIDs      []ObjectId  `json:"assetIds"`
	AttachmentIDs *[]ObjectId `json:"attachmentIds,omitempty"`
	Reason        *string     `json:"reason,omitempty"`
	Status        AssetStatus `json:"status"`

	// ValidOnly If true, enqueue the valid rows and record invalid ones as job row errors instead of failing the whole request. Default false (strict: any invalid row → 400, nothing enqueued).
	ValidOnly *bool `json:"validOnly,omitempty"`
}

// BulkTransferRequest defines model for BulkTransferRequest.
type BulkTransferRequest struct {
	AssetIDs      []ObjectId  `json:"assetIds"`
	AttachmentIDs *[]ObjectId `json:"attachmentIds,omitempty"`

	// ExpectedReturnDate Applied to every asset in the batch that is NOT returning to its home venue.
	ExpectedReturnDate *time.Time `json:"expectedReturnDate,omitempty"`
	Notes              *string    `json:"notes,omitempty"`
	ToVenueID          ObjectId   `json:"toVenueId"`

	// ValidOnly If true, enqueue the valid rows and record invalid ones as job row errors instead of failing the whole request. Default false (strict: any invalid row → 400, nothing enqueued).
	ValidOnly *bool `json:"validOnly,omitempty"`
}

// Category defines model for Category.
type Category struct {
	CreatedAt    time.Time             `bson:"createdAt" json:"createdAt"`
	CustomFields []CategoryCustomField `bson:"customFields" json:"customFields"`
	Description  *string               `bson:"description,omitempty" json:"description,omitempty"`
	ID           ObjectId              `bson:"_id,omitempty" json:"id"`
	IsActive     bool                  `bson:"isActive" json:"isActive"`
	Name         string                `bson:"name" json:"name"`
	Slug         string                `bson:"slug" json:"slug"`
	UpdatedAt    time.Time             `bson:"updatedAt" json:"updatedAt"`
}

// CategoryCustomField defines model for CategoryCustomField.
type CategoryCustomField struct {
	Key      string          `bson:"key" json:"key"`
	Label    string          `bson:"label" json:"label"`
	Required bool            `bson:"required" json:"required"`
	Type     CustomFieldType `bson:"type" json:"type"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	// Current The caller's current password, used to re-authenticate the change.
	Current string `json:"current"`

	// Next The new password. 8-72 characters (bcrypt's 72-byte ceiling).
	Next string `json:"next"`
}

// CommitImportRequest defines model for CommitImportRequest.
type CommitImportRequest struct {
	ImportJobID ObjectId          `json:"importJobId"`
	Options     *ImportJobOptions `json:"options,omitempty"`
}

// ConditionUpdate defines model for ConditionUpdate.
type ConditionUpdate struct {
	AttachmentIDs *[]ObjectId    `json:"attachmentIds,omitempty"`
	Condition     AssetCondition `json:"condition"`
	Notes         *string        `json:"notes,omitempty"`
}

// CreateAssetRequest defines model for CreateAssetRequest.
type CreateAssetRequest struct {
	CategoryID        ObjectId                `json:"categoryId"`
	Condition         AssetCondition          `json:"condition"`
	CurrentVenueID    *ObjectId               `json:"currentVenueId,omitempty"`
	DepartmentID      *ObjectId               `json:"departmentId,omitempty"`
	HomeVenueID       ObjectId                `json:"homeVenueId"`
	Name              string                  `json:"name"`
	Notes             *string                 `json:"notes,omitempty"`
	Photos            *[]string               `json:"photos,omitempty"`
	PurchaseDate      *time.Time              `json:"purchaseDate,omitempty"`
	PurchaseOrderID   *ObjectId               `json:"purchaseOrderId,omitempty"`
	ResponsibleUserID *ObjectId               `json:"responsibleUserId,omitempty"`
	SerialNumber      *string                 `json:"serialNumber,omitempty"`
	Specs             *map[string]interface{} `json:"specs,omitempty"`
}

// CreateCategoryRequest defines model for CreateCategoryRequest.
type CreateCategoryRequest struct {
	CustomFields *[]CategoryCustomField `json:"customFields,omitempty"`
	Description  *string                `json:"description,omitempty"`
	IsActive     *bool                  `json:"isActive,omitempty"`
	Name         string                 `json:"name"`
	Slug         string                 `json:"slug"`
}

// CreateDepartmentRequest defines model for CreateDepartmentRequest.
type CreateDepartmentRequest struct {
	Code        string  `json:"code"`
	Description *string `json:"description,omitempty"`
	IsActive    *bool   `json:"isActive,omitempty"`
	Name        string  `json:"name"`
}

// CreatePurchaseOrderRequest defines model for CreatePurchaseOrderRequest.
type CreatePurchaseOrderRequest struct {
	Attachments       *[]string               `json:"attachments,omitempty"`
	LineItems         []PurchaseOrderLineItem `json:"lineItems"`
	Notes             *string                 `json:"notes,omitempty"`
	OrderDate         time.Time               `json:"orderDate"`
	PONumber          string                  `json:"poNumber"`
	ResponsibleUserID ObjectId                `json:"responsibleUserId"`
	Supplier          PurchaseOrderSupplier   `json:"supplier"`
}

// CreateRepairRequest defines model for CreateRepairRequest.
type CreateRepairRequest struct {
	AssetID ObjectId `json:"assetId"`
	Issue   string   `json:"issue"`
	Notes   *string  `json:"notes,omitempty"`
	Vendor  *string  `json:"vendor,omitempty"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Email         openapi_types.Email `json:"email"`
	Name          string              `json:"name"`
	NotifyByEmail *bool               `json:"notifyByEmail,omitempty"`
	Password      string              `json:"password"`
	Phone         *string             `json:"phone,omitempty"`
	Position      string              `json:"position"`
	Role          Role                `json:"role"`
	VenueIDs      *[]ObjectId         `json:"venueIds,omitempty"`
}

// CreateVenueRequest defines model for CreateVenueRequest.
type CreateVenueRequest struct {
	Address  *string `json:"address,omitempty"`
	City     *string `json:"city,omitempty"`
	Code     string  `json:"code"`
	IsActive *bool   `json:"isActive,omitempty"`
	Name     string  `json:"name"`
	Type     string  `json:"type"`
}

// CursorPagination defines model for CursorPagination.
type CursorPagination struct {
	HasMore bool `json:"hasMore"`
	Limit   int  `json:"limit"`

	// NextCursor Opaque token; pass back as the `cursor` query param to fetch the next page. Present only when hasMore is true.
	NextCursor *string `json:"nextCursor,omitempty"`
}

// CustomFieldType defines model for CustomFieldType.
type CustomFieldType string

// DashboardSummary defines model for DashboardSummary.
type DashboardSummary struct {
	AwayFromHome int                   `json:"awayFromHome"`
	ByStatus     map[string]int        `json:"byStatus"`
	ByVenue      []DashboardVenueCount `json:"byVenue"`
	InRepair     int                   `json:"inRepair"`
	Overdue      int                   `json:"overdue"`
	TotalAssets  int                   `json:"totalAssets"`
}

// DashboardVenueCount defines model for DashboardVenueCount.
type DashboardVenueCount struct {
	Count     int      `json:"count"`
	VenueID   ObjectId `json:"venueId"`
	VenueName string   `json:"venueName"`
}

// Department defines model for Department.
type Department struct {
	Code        string    `bson:"code" json:"code"`
	CreatedAt   time.Time `bson:"createdAt" json:"createdAt"`
	Description *string   `bson:"description,omitempty" json:"description,omitempty"`
	ID          ObjectId  `bson:"_id,omitempty" json:"id"`
	IsActive    bool      `bson:"isActive" json:"isActive"`
	Name        string    `bson:"name" json:"name"`
	UpdatedAt   time.Time `bson:"updatedAt" json:"updatedAt"`
	VenueID     ObjectId  `bson:"venueId" json:"venueId"`
}

// DepartmentAssetCountRow defines model for DepartmentAssetCountRow.
type DepartmentAssetCountRow struct {
	Count          int      `json:"count"`
	DepartmentID   ObjectId `json:"departmentId"`
	DepartmentName string   `json:"departmentName"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error ErrorPayload `json:"error"`
}

// ErrorPayload defines model for ErrorPayload.
type ErrorPayload struct {
	Fields  *map[string]string `json:"fields,omitempty"`
	Kind    ErrorPayloadKind   `json:"kind"`
	Message string             `json:"message"`
}

// ErrorPayloadKind defines model for ErrorPayload.Kind.
type ErrorPayloadKind string

// ImportConflictPolicy defines model for ImportConflictPolicy.
type ImportConflictPolicy string

// ImportJob defines model for ImportJob.
type ImportJob struct {
	CompletedAt *time.Time       `bson:"completedAt,omitempty" json:"completedAt,omitempty"`
	Counts      ImportJobCounts  `bson:"counts" json:"counts"`
	CreatedAt   time.Time        `bson:"createdAt" json:"createdAt"`
	Errors      []ImportRowError `bson:"errors" json:"errors"`
	Filename    string           `bson:"filename" json:"filename"`
	ID          ObjectId         `bson:"_id,omitempty" json:"id"`
	Options     ImportJobOptions `bson:"options" json:"options"`
	Status      ImportJobStatus  `bson:"status" json:"status"`
	UploadedBy  ObjectId         `bson:"uploadedBy" json:"uploadedBy"`
}

// ImportJobCounts defines model for ImportJobCounts.
type ImportJobCounts struct {
	AssetsCreated int `bson:"assetsCreated" json:"assetsCreated"`
	PosCreated    int `bson:"posCreated" json:"posCreated"`
	PosTotal      int `bson:"posTotal" json:"posTotal"`
	RowsErrored   int `bson:"rowsErrored" json:"rowsErrored"`
	RowsSkipped   int `bson:"rowsSkipped" json:"rowsSkipped"`
}

// ImportJobOptions defines model for ImportJobOptions.
type ImportJobOptions struct {
	// ImportValidOnly If true, commit valid rows and skip errored ones rather than rejecting the whole job.
	ImportValidOnly *bool `bson:"importValidOnly,omitempty" json:"importValidOnly,omitempty"`

	// OnConflict Behaviour when a poNumber already exists. Default: error.
	OnConflict *ImportConflictPolicy `bson:"onConflict,omitempty" json:"onConflict,omitempty"`
}

// ImportJobStatus defines model for ImportJobStatus.
type ImportJobStatus string

// ImportPreview defines model for ImportPreview.
type ImportPreview struct {
	Job        ImportJob         `json:"job"`
	PosPreview []ImportPreviewPO `json:"posPreview"`
}

// ImportPreviewPO defines model for ImportPreviewPO.
type ImportPreviewPO struct {
	AssetCount   int       `json:"assetCount"`
	Categories   *[]string `json:"categories,omitempty"`
	LineItems    int       `json:"lineItems"`
	PoNumber     string    `json:"poNumber"`
	SkipExisting *bool     `json:"skipExisting,omitempty"`
	Venues       *[]string `json:"venues,omitempty"`
}

// ImportRowError defines model for ImportRowError.
type ImportRowError struct {
	Field   *string `bson:"field,omitempty" json:"field,omitempty"`
	Message string  `bson:"message" json:"message"`

	// Row 1-based row in the uploaded file (header = 1, first data row = 2).
	Row int `bson:"row" json:"row"`
}

// InventoryByVenueRow defines model for InventoryByVenueRow.
type InventoryByVenueRow struct {
	ByDepartment *[]DepartmentAssetCountRow `json:"byDepartment,omitempty"`
	ByStatus     *map[string]int            `json:"byStatus,omitempty"`
	Total        int                        `json:"total"`
	VenueID      ObjectId                   `json:"venueId"`
	VenueName    string                     `json:"venueName"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Meta defines model for Meta.
type Meta struct {
	Cursor     *CursorPagination `json:"cursor,omitempty"`
	Pagination *Pagination       `json:"pagination,omitempty"`
}

// Movement defines model for Movement.
type Movement struct {
	AssetID       ObjectId    `bson:"assetId" json:"assetId"`
	AttachmentIDs *[]ObjectId `bson:"attachmentIds,omitempty" json:"attachmentIds,omitempty"`

	// Attachments Populated only in history responses via server-side enrichment; never persisted.
	Attachments *[]AttachmentMeta `bson:"-" json:"attachments,omitempty"`

	// BulkJobID Provenance stamp for movements written by an async bulk-asset job (mirrors importJobId on assets/POs). Absent for single-asset actions.
	BulkJobID          *ObjectId       `bson:"bulkJobId,omitempty" json:"bulkJobId,omitempty"`
	ExpectedReturnDate *time.Time      `bson:"expectedReturnDate,omitempty" json:"expectedReturnDate,omitempty"`
	FromCondition      *AssetCondition `bson:"fromCondition,omitempty" json:"fromCondition,omitempty"`
	FromStatus         *AssetStatus    `bson:"fromStatus,omitempty" json:"fromStatus,omitempty"`
	FromUserID         *ObjectId       `bson:"fromUserId,omitempty" json:"fromUserId,omitempty"`
	FromVenueID        *ObjectId       `bson:"fromVenueId,omitempty" json:"fromVenueId,omitempty"`
	ID                 ObjectId        `bson:"_id,omitempty" json:"id"`
	Notes              *string         `bson:"notes,omitempty" json:"notes,omitempty"`
	PerformedAt        time.Time       `bson:"performedAt" json:"performedAt"`
	PerformedBy        ObjectId        `bson:"performedBy" json:"performedBy"`
	Reason             *string         `bson:"reason,omitempty" json:"reason,omitempty"`
	ToCondition        *AssetCondition `bson:"toCondition,omitempty" json:"toCondition,omitempty"`
	ToStatus           *AssetStatus    `bson:"toStatus,omitempty" json:"toStatus,omitempty"`
	ToUserID           *ObjectId       `bson:"toUserId,omitempty" json:"toUserId,omitempty"`
	ToVenueID          *ObjectId       `bson:"toVenueId,omitempty" json:"toVenueId,omitempty"`
	Type               MovementType    `bson:"type" json:"type"`
}

// MovementType defines model for MovementType.
type MovementType string

// Notification defines model for Notification.
type Notification struct {
	AssetID   *ObjectId           `bson:"assetId,omitempty" json:"assetId,omitempty"`
	Attempts  int                 `bson:"attempts" json:"attempts"`
	Body      string              `bson:"body" json:"body"`
	Channel   NotificationChannel `bson:"channel" json:"channel"`
	CreatedAt time.Time           `bson:"createdAt" json:"createdAt"`
	Error     *string             `bson:"error,omitempty" json:"error,omitempty"`
	ID        ObjectId            `bson:"_id,omitempty" json:"id"`

	// RecipientEmail Snapshotted at enqueue time so worker sends do not need a DB lookup.
	RecipientEmail  openapi_types.Email `bson:"recipientEmail" json:"recipientEmail"`
	RecipientUserID ObjectId            `bson:"recipientUserId" json:"recipientUserId"`
	SentAt          *time.Time          `bson:"sentAt,omitempty" json:"sentAt,omitempty"`
	Status          NotificationStatus  `bson:"status" json:"status"`
	Subject         string              `bson:"subject" json:"subject"`
	Type            NotificationType    `bson:"type" json:"type"`
}

// NotificationChannel defines model for NotificationChannel.
type NotificationChannel string

// NotificationStatus defines model for NotificationStatus.
type NotificationStatus string

// NotificationType defines model for NotificationType.
type NotificationType string

// ObjectId defines model for ObjectId.
type ObjectId = bson.ObjectID

// Pagination defines model for Pagination.
type Pagination struct {
	Limit      int   `json:"limit"`
	Page       int   `json:"page"`
	Total      int64 `json:"total"`
	TotalPages int   `json:"totalPages"`
}

// PurchaseOrder defines model for PurchaseOrder.
type PurchaseOrder struct {
	Attachments       *[]string               `bson:"attachments,omitempty" json:"attachments,omitempty"`
	CreatedAt         time.Time               `bson:"createdAt" json:"createdAt"`
	CreatedBy         ObjectId                `bson:"createdBy" json:"createdBy"`
	ID                ObjectId                `bson:"_id,omitempty" json:"id"`
	ImportJobID       *ObjectId               `bson:"importJobId,omitempty" json:"importJobId,omitempty"`
	LineItems         []PurchaseOrderLineItem `bson:"lineItems" json:"lineItems"`
	Notes             *string                 `bson:"notes,omitempty" json:"notes,omitempty"`
	OrderDate         time.Time               `bson:"orderDate" json:"orderDate"`
	PONumber          string                  `bson:"poNumber" json:"poNumber"`
	ReceivedDate      *time.Time              `bson:"receivedDate,omitempty" json:"receivedDate,omitempty"`
	ResponsibleUserID ObjectId                `bson:"responsibleUserId" json:"responsibleUserId"`
	Status            PurchaseOrderStatus     `bson:"status" json:"status"`
	Supplier          PurchaseOrderSupplier   `bson:"supplier" json:"supplier"`
	UpdatedAt         time.Time               `bson:"updatedAt" json:"updatedAt"`
}

// PurchaseOrderLineItem defines model for PurchaseOrderLineItem.
type PurchaseOrderLineItem struct {
	CategoryID ObjectId `bson:"categoryId" json:"categoryId"`
	Name       string   `bson:"name" json:"name"`
	Quantity   int      `bson:"quantity" json:"quantity"`
}

// PurchaseOrderStatus defines model for PurchaseOrderStatus.
type PurchaseOrderStatus string

// PurchaseOrderSupplier defines model for PurchaseOrderSupplier.
type PurchaseOrderSupplier struct {
	Contact *string `bson:"contact,omitempty" json:"contact,omitempty"`
	Name    string  `bson:"name" json:"name"`
}

// ReceivePurchaseOrderRequest defines model for ReceivePurchaseOrderRequest.
type ReceivePurchaseOrderRequest struct {
	// DepartmentID Optional home department for every asset generated by this receive. Must belong to venueId.
	DepartmentID *ObjectId `json:"departmentId,omitempty"`

	// VenueID Home venue for every asset generated by this receive.
	VenueID ObjectId `json:"venueId"`
}

// ReceivePurchaseOrderResponse defines model for ReceivePurchaseOrderResponse.
type ReceivePurchaseOrderResponse struct {
	GeneratedAssetIDs []ObjectId    `json:"generatedAssetIds"`
	PurchaseOrder     PurchaseOrder `json:"purchaseOrder"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refreshToken"`
}

// Repair defines model for Repair.
type Repair struct {
	AssetID    ObjectId     `bson:"assetId" json:"assetId"`
	CreatedAt  time.Time    `bson:"createdAt" json:"createdAt"`
	ID         ObjectId     `bson:"_id,omitempty" json:"id"`
	Issue      string       `bson:"issue" json:"issue"`
	Notes      *string      `bson:"notes,omitempty" json:"notes,omitempty"`
	ReportedAt time.Time    `bson:"reportedAt" json:"reportedAt"`
	ReportedBy ObjectId     `bson:"reportedBy" json:"reportedBy"`
	Resolution *string      `bson:"resolution,omitempty" json:"resolution,omitempty"`
	ReturnedAt *time.Time   `bson:"returnedAt,omitempty" json:"returnedAt,omitempty"`
	SentAt     *time.Time   `bson:"sentAt,omitempty" json:"sentAt,omitempty"`
	Status     RepairStatus `bson:"status" json:"status"`
	UpdatedAt  time.Time    `bson:"updatedAt" json:"updatedAt"`
	Vendor     *string      `bson:"vendor,omitempty" json:"vendor,omitempty"`
}

// RepairStatus defines model for RepairStatus.
type RepairStatus string

// Role defines model for Role.
type Role string

// ScanAssetView Read-only asset view returned by the authenticated scan endpoint. Carries no attachment data — attachment metadata is exclusive to GET /assets/{id}/history.
type ScanAssetView struct {
	Asset            Asset   `json:"asset"`
	CategoryName     *string `json:"categoryName,omitempty"`
	CurrentVenueName *string `json:"currentVenueName,omitempty"`
	DepartmentName   *string `json:"departmentName,omitempty"`
	HomeVenueName    *string `json:"homeVenueName,omitempty"`

	// ResponsiblePerson Responsible person shown on the authenticated scan view. Every viewer is authenticated AND authorized for the asset, so full contact details (email/phone) are included.
	ResponsiblePerson *ScanUserContact `json:"responsiblePerson,omitempty"`
}

// ScanUserContact Responsible person shown on the authenticated scan view. Every viewer is authenticated AND authorized for the asset, so full contact details (email/phone) are included.
type ScanUserContact struct {
	Email    openapi_types.Email `json:"email"`
	ID       ObjectId            `json:"id"`
	Name     string              `json:"name"`
	Phone    *string             `json:"phone,omitempty"`
	Position string              `json:"position"`
	Role     Role                `json:"role"`
}

// StatusChangeRequest defines model for StatusChangeRequest.
type StatusChangeRequest struct {
	AttachmentIDs *[]ObjectId `json:"attachmentIds,omitempty"`
	Reason        *string     `json:"reason,omitempty"`
	Status        AssetStatus `json:"status"`
}

// TokenPair defines model for TokenPair.
type TokenPair struct {
	// AccessExp unix seconds
	AccessExp   int64  `json:"accessExp"`
	AccessToken string `json:"accessToken"`

	// RefreshExp unix seconds
	RefreshExp   int64  `json:"refreshExp"`
	RefreshToken string `json:"refreshToken"`
}

// TransferAssetRequest defines model for TransferAssetRequest.
type TransferAssetRequest struct {
	AttachmentIDs *[]ObjectId `json:"attachmentIds,omitempty"`

	// ExpectedReturnDate If set, the asset is a temporary transfer subject to overdue checks.
	ExpectedReturnDate *time.Time `json:"expectedReturnDate,omitempty"`
	Notes              *string    `json:"notes,omitempty"`
	ToVenueID          ObjectId   `json:"toVenueId"`
}

// UpdateAssetRequest defines model for UpdateAssetRequest.
type UpdateAssetRequest struct {
	CategoryID   *ObjectId               `json:"categoryId,omitempty"`
	Condition    *AssetCondition         `json:"condition,omitempty"`
	DepartmentID *ObjectId               `json:"departmentId,omitempty"`
	HomeVenueID  *ObjectId               `json:"homeVenueId,omitempty"`
	IsActive     *bool                   `json:"isActive,omitempty"`
	Name         *string                 `json:"name,omitempty"`
	Notes        *string                 `json:"notes,omitempty"`
	Photos       *[]string               `json:"photos,omitempty"`
	SerialNumber *string                 `json:"serialNumber,omitempty"`
	Specs        *map[string]interface{} `json:"specs,omitempty"`
}

// UpdateCategoryRequest defines model for UpdateCategoryRequest.
type UpdateCategoryRequest struct {
	CustomFields *[]CategoryCustomField `json:"customFields,omitempty"`
	Description  *string                `json:"description,omitempty"`
	IsActive     *bool                  `json:"isActive,omitempty"`
	Name         *string                `json:"name,omitempty"`
	Slug         *string                `json:"slug,omitempty"`
}

// UpdateDepartmentRequest defines model for UpdateDepartmentRequest.
type UpdateDepartmentRequest struct {
	Code        *string `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
	IsActive    *bool   `json:"isActive,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// UpdateNotificationPreferencesRequest defines model for UpdateNotificationPreferencesRequest.
type UpdateNotificationPreferencesRequest struct {
	NotifyByEmail bool `json:"notifyByEmail"`
}

// UpdatePurchaseOrderRequest defines model for UpdatePurchaseOrderRequest.
type UpdatePurchaseOrderRequest struct {
	Attachments       *[]string                `json:"attachments,omitempty"`
	LineItems         *[]PurchaseOrderLineItem `json:"lineItems,omitempty"`
	Notes             *string                  `json:"notes,omitempty"`
	OrderDate         *time.Time               `json:"orderDate,omitempty"`
	PONumber          *string                  `json:"poNumber,omitempty"`
	ResponsibleUserID *ObjectId                `json:"responsibleUserId,omitempty"`
	Status            *PurchaseOrderStatus     `json:"status,omitempty"`
	Supplier          *PurchaseOrderSupplier   `json:"supplier,omitempty"`
}

// UpdateRepairRequest defines model for UpdateRepairRequest.
type UpdateRepairRequest struct {
	Notes      *string       `json:"notes,omitempty"`
	Resolution *string       `json:"resolution,omitempty"`
	ReturnedAt *time.Time    `json:"returnedAt,omitempty"`
	SentAt     *time.Time    `json:"sentAt,omitempty"`
	Status     *RepairStatus `json:"status,omitempty"`
	Vendor     *string       `json:"vendor,omitempty"`
}

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	Email         *openapi_types.Email `json:"email,omitempty"`
	IsActive      *bool                `json:"isActive,omitempty"`
	Name          *string              `json:"name,omitempty"`
	NotifyByEmail *bool                `json:"notifyByEmail,omitempty"`
	Password      *string              `json:"password,omitempty"`
	Phone         *string              `json:"phone,omitempty"`
	Position      *string              `json:"position,omitempty"`
	Role          *Role                `json:"role,omitempty"`
	VenueIDs      *[]ObjectId          `json:"venueIds,omitempty"`
}

// UpdateVenueRequest defines model for UpdateVenueRequest.
type UpdateVenueRequest struct {
	Address  *string `json:"address,omitempty"`
	City     *string `json:"city,omitempty"`
	Code     *string `json:"code,omitempty"`
	IsActive *bool   `json:"isActive,omitempty"`
	Name     *string `json:"name,omitempty"`
	Type     *string `json:"type,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt     time.Time           `bson:"createdAt" json:"createdAt"`
	Email         openapi_types.Email `bson:"email" json:"email"`
	ID            ObjectId            `bson:"_id,omitempty" json:"id"`
	IsActive      bool                `bson:"isActive" json:"isActive"`
	Name          string              `bson:"name" json:"name"`
	NotifyByEmail bool                `bson:"notifyByEmail" json:"notifyByEmail"`
	PasswordHash  string              `bson:"passwordHash" json:"-"`
	Phone         *string             `bson:"phone,omitempty" json:"phone,omitempty"`

	// Position Job title, e.g. "IT Staff", "Event Manager"
	Position  string     `bson:"position" json:"position"`
	Role      Role       `bson:"role" json:"role"`
	UpdatedAt time.Time  `bson:"updatedAt" json:"updatedAt"`
	VenueIDs  []ObjectId `bson:"venueIds" json:"venueIds"`
}

// Venue defines model for Venue.
type Venue struct {
	Address   *string   `bson:"address,omitempty" json:"address,omitempty"`
	City      *string   `bson:"city,omitempty" json:"city,omitempty"`
	Code      string    `bson:"code" json:"code"`
	CreatedAt time.Time `bson:"createdAt" json:"createdAt"`
	ID        ObjectId  `bson:"_id,omitempty" json:"id"`
	IsActive  bool      `bson:"isActive" json:"isActive"`
	Name      string    `bson:"name" json:"name"`
	Type      string    `bson:"type" json:"type"`
	UpdatedAt time.Time `bson:"updatedAt" json:"updatedAt"`
}

// IdPath defines model for IdPath.
type IdPath = string

// LimitParam defines model for LimitParam.
type LimitParam = int

// PageParam defines model for PageParam.
type PageParam = int

// QrTokenPath defines model for QrTokenPath.
type QrTokenPath = string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = ErrorEnvelope

// GetAssetsParams defines parameters for GetAssets.
type GetAssetsParams struct {
	Page         *PageParam   `form:"page,omitempty" json:"page,omitempty"`
	Limit        *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
	Venue        *string      `form:"venue,omitempty" json:"venue,omitempty"`
	CurrentVenue *string      `form:"currentVenue,omitempty" json:"currentVenue,omitempty"`
	Category     *string      `form:"category,omitempty" json:"category,omitempty"`
	Department   *string      `form:"department,omitempty" json:"department,omitempty"`
	Status       *AssetStatus `form:"status,omitempty" json:"status,omitempty"`
	Responsible  *string      `form:"responsible,omitempty" json:"responsible,omitempty"`
	Away         *bool        `form:"away,omitempty" json:"away,omitempty"`
	Overdue      *bool        `form:"overdue,omitempty" json:"overdue,omitempty"`

	// Q free-text on name/serialNumber/assetTag
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// GetAssetsBulkJobsParams defines parameters for GetAssetsBulkJobs.
type GetAssetsBulkJobsParams struct {
	Status *BulkJobStatus `form:"status,omitempty" json:"status,omitempty"`
	Type   *BulkJobType   `form:"type,omitempty" json:"type,omitempty"`
}

// PostAttachmentsMultipartBody defines parameters for PostAttachments.
type PostAttachmentsMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// GetCategoriesParams defines parameters for GetCategories.
type GetCategoriesParams struct {
	Page  *PageParam  `form:"page,omitempty" json:"page,omitempty"`
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostImportsPurchaseOrdersValidateMultipartBody defines parameters for PostImportsPurchaseOrdersValidate.
type PostImportsPurchaseOrdersValidateMultipartBody struct {
	File openapi_types.File `json:"file"`

	// Options JSON-encoded ImportJobOptions.
	Options *string `json:"options,omitempty"`
}

// GetNotificationsParams defines parameters for GetNotifications.
type GetNotificationsParams struct {
	Page   *PageParam          `form:"page,omitempty" json:"page,omitempty"`
	Limit  *LimitParam         `form:"limit,omitempty" json:"limit,omitempty"`
	Status *NotificationStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetPurchaseOrdersParams defines parameters for GetPurchaseOrders.
type GetPurchaseOrdersParams struct {
	Page        *PageParam           `form:"page,omitempty" json:"page,omitempty"`
	Limit       *LimitParam          `form:"limit,omitempty" json:"limit,omitempty"`
	Status      *PurchaseOrderStatus `form:"status,omitempty" json:"status,omitempty"`
	Responsible *string              `form:"responsible,omitempty" json:"responsible,omitempty"`
}

// GetRepairsParams defines parameters for GetRepairs.
type GetRepairsParams struct {
	Page    *PageParam    `form:"page,omitempty" json:"page,omitempty"`
	Limit   *LimitParam   `form:"limit,omitempty" json:"limit,omitempty"`
	Status  *RepairStatus `form:"status,omitempty" json:"status,omitempty"`
	AssetId *string       `form:"assetId,omitempty" json:"assetId,omitempty"`
}

// GetReportsAssetsAwayParams defines parameters for GetReportsAssetsAway.
type GetReportsAssetsAwayParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque keyset cursor from a previous response's meta.cursor.nextCursor. Omit for the first page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetReportsAssetsOverdueParams defines parameters for GetReportsAssetsOverdue.
type GetReportsAssetsOverdueParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque keyset cursor from a previous response's meta.cursor.nextCursor. Omit for the first page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetReportsByDepartmentParams defines parameters for GetReportsByDepartment.
type GetReportsByDepartmentParams struct {
	// Venue Optional venue scope; when omitted, admins get all venues.
	Venue *string `form:"venue,omitempty" json:"venue,omitempty"`
}

// GetReportsInRepairParams defines parameters for GetReportsInRepair.
type GetReportsInRepairParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque keyset cursor from a previous response's meta.cursor.nextCursor. Omit for the first page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	Page  *PageParam  `form:"page,omitempty" json:"page,omitempty"`
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetVenuesParams defines parameters for GetVenues.
type GetVenuesParams struct {
	Page  *PageParam  `form:"page,omitempty" json:"page,omitempty"`
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetVenuesVenueIdDepartmentsParams defines parameters for GetVenuesVenueIdDepartments.
type GetVenuesVenueIdDepartmentsParams struct {
	Page  *PageParam  `form:"page,omitempty" json:"page,omitempty"`
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostAssetsJSONRequestBody defines body for PostAssets for application/json ContentType.
type PostAssetsJSONRequestBody = CreateAssetRequest

// PostAssetsBulkAssignJSONRequestBody defines body for PostAssetsBulkAssign for application/json ContentType.
type PostAssetsBulkAssignJSONRequestBody = BulkAssignRequest

// PostAssetsBulkIdsJSONRequestBody defines body for PostAssetsBulkIds for application/json ContentType.
type PostAssetsBulkIdsJSONRequestBody = BulkIdsRequest

// PostAssetsBulkStatusJSONRequestBody defines body for PostAssetsBulkStatus for application/json ContentType.
type PostAssetsBulkStatusJSONRequestBody = BulkStatusRequest

// PostAssetsBulkTransferJSONRequestBody defines body for PostAssetsBulkTransfer for application/json ContentType.
type PostAssetsBulkTransferJSONRequestBody = BulkTransferRequest

// PostAssetsConditionBulkJSONRequestBody defines body for PostAssetsConditionBulk for application/json ContentType.
type PostAssetsConditionBulkJSONRequestBody = BulkConditionUpdate

// PostAssetsQrBulkJSONRequestBody defines body for PostAssetsQrBulk for application/json ContentType.
type PostAssetsQrBulkJSONRequestBody = BulkQrRequest

// PutAssetsIdJSONRequestBody defines body for PutAssetsId for application/json ContentType.
type PutAssetsIdJSONRequestBody = UpdateAssetRequest

// PostAssetsIdAssignJSONRequestBody defines body for PostAssetsIdAssign for application/json ContentType.
type PostAssetsIdAssignJSONRequestBody = AssignCustodyRequest

// PostAssetsIdConditionJSONRequestBody defines body for PostAssetsIdCondition for application/json ContentType.
type PostAssetsIdConditionJSONRequestBody = ConditionUpdate

// PostAssetsIdStatusJSONRequestBody defines body for PostAssetsIdStatus for application/json ContentType.
type PostAssetsIdStatusJSONRequestBody = StatusChangeRequest

// PostAssetsIdTransferJSONRequestBody defines body for PostAssetsIdTransfer for application/json ContentType.
type PostAssetsIdTransferJSONRequestBody = TransferAssetRequest

// PostAttachmentsMultipartRequestBody defines body for PostAttachments for multipart/form-data ContentType.
type PostAttachmentsMultipartRequestBody PostAttachmentsMultipartBody

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthRefreshJSONRequestBody defines body for PostAuthRefresh for application/json ContentType.
type PostAuthRefreshJSONRequestBody = RefreshRequest

// PostCategoriesJSONRequestBody defines body for PostCategories for application/json ContentType.
type PostCategoriesJSONRequestBody = CreateCategoryRequest

// PutCategoriesIdJSONRequestBody defines body for PutCategoriesId for application/json ContentType.
type PutCategoriesIdJSONRequestBody = UpdateCategoryRequest

// PostImportsPurchaseOrdersCommitJSONRequestBody defines body for PostImportsPurchaseOrdersCommit for application/json ContentType.
type PostImportsPurchaseOrdersCommitJSONRequestBody = CommitImportRequest

// PostImportsPurchaseOrdersValidateMultipartRequestBody defines body for PostImportsPurchaseOrdersValidate for multipart/form-data ContentType.
type PostImportsPurchaseOrdersValidateMultipartRequestBody PostImportsPurchaseOrdersValidateMultipartBody

// PutMeNotificationPreferencesJSONRequestBody defines body for PutMeNotificationPreferences for application/json ContentType.
type PutMeNotificationPreferencesJSONRequestBody = UpdateNotificationPreferencesRequest

// PostMePasswordJSONRequestBody defines body for PostMePassword for application/json ContentType.
type PostMePasswordJSONRequestBody = ChangePasswordRequest

// PostPurchaseOrdersJSONRequestBody defines body for PostPurchaseOrders for application/json ContentType.
type PostPurchaseOrdersJSONRequestBody = CreatePurchaseOrderRequest

// PutPurchaseOrdersIdJSONRequestBody defines body for PutPurchaseOrdersId for application/json ContentType.
type PutPurchaseOrdersIdJSONRequestBody = UpdatePurchaseOrderRequest

// PostPurchaseOrdersIdReceiveJSONRequestBody defines body for PostPurchaseOrdersIdReceive for application/json ContentType.
type PostPurchaseOrdersIdReceiveJSONRequestBody = ReceivePurchaseOrderRequest

// PostRepairsJSONRequestBody defines body for PostRepairs for application/json ContentType.
type PostRepairsJSONRequestBody = CreateRepairRequest

// PutRepairsIdJSONRequestBody defines body for PutRepairsId for application/json ContentType.
type PutRepairsIdJSONRequestBody = UpdateRepairRequest

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = CreateUserRequest

// PutUsersIdJSONRequestBody defines body for PutUsersId for application/json ContentType.
type PutUsersIdJSONRequestBody = UpdateUserRequest

// PostVenuesJSONRequestBody defines body for PostVenues for application/json ContentType.
type PostVenuesJSONRequestBody = CreateVenueRequest

// PutVenuesIdJSONRequestBody defines body for PutVenuesId for application/json ContentType.
type PutVenuesIdJSONRequestBody = UpdateVenueRequest

// PostVenuesVenueIdDepartmentsJSONRequestBody defines body for PostVenuesVenueIdDepartments for application/json ContentType.
type PostVenuesVenueIdDepartmentsJSONRequestBody = CreateDepartmentRequest

// PutVenuesVenueIdDepartmentsIdJSONRequestBody defines body for PutVenuesVenueIdDepartmentsId for application/json ContentType.
type PutVenuesVenueIdDepartmentsIdJSONRequestBody = UpdateDepartmentRequest
